observation_date: # 01/27/24
target_list: targets/Messier
type_filter: # e.g. Galaxy, Nebula 
output_dir: out
live_mode: true

location:
  longitude: 1d43m36.77s
  latitude:  51d24m57.64s
  elevation: 140
  timezone: Europe/London

environment:
  pressure: 1.022
  temperature: 18
  relative_humidity: 0.7

constraints:
  altitude_constraint_min: 30  # in deg above horizon
  altitude_constraint_max: 80  # in deg above horizon
  airmass_constraint: 2  # 30° to 90°, 2 = 1/cos(60) 
  size_constraint_min: 10  # in arc minutes
  size_constraint_max: 300  # in arc minutes

  moon_separation_min: 45  # in degrees

  # if set to true, moon_separation_min is derived from the moon illumination
  # percentage and overwrites moon_separation_min. 1% corresponds 1°.
  moon_separation_use_illumination: true

  # object needs to be within the constraints for at least 50% of darkness
  fraction_of_time_observable_threshold: 0.5

  # maximum number of targets to calculate
  max_number_within_threshold: 60

  # true : meaning that azimuth is shown increasing counter-clockwise (ccw), or with north
  #        at top, east at left, etc.
  # false: show azimuth increasing clockwise (cw).
  north_to_east_ccw: false

output_datestamp: false

# personal bucket list to always include
bucket_list:
  - IC 434
  - NGC 2359
  - M 16

done_list:
  - IC 1795
  - LBN 535

custom_targets:
  - name: NGC 4395
    description: NGC 4395
    type: Galaxy
    constellation: Canes Venatici
    size: 13
    ra: 12 25 48
    dec: +33 32 48
    mag: 10.0
  - name: NGC 3227
    description: Galaxy duo NGC 3226
    type: Galaxy
    constellation: Leo
    size: 4
    ra: 10 23 30
    dec: +19 51 54
    mag: 10.4
  - name: LBN 105
    description: SH2-73
    type: Molecular Cloud
    constellation: Hercules
    size: 75
    ra: 16 11 7.6
    dec: +21 52 26.4
    mag: 0

# Horizon
horizon:
  # Step size in degrees
  step_size: 5
  # Anchor points of the horizon
  # Should start with an azimuth of 0 and end with 360 degrees
  anchor_points:
    - alt: 20
      az: 0
    - alt: 20
      az: 52
    - alt: 30
      az: 60
    - alt: 49
      az: 90
    - alt: 52
      az: 135
    - alt: 21
      az: 150
    - alt: 16
      az: 176
    - alt: 14
      az: 222
    - alt: 34
      az: 241
    - alt: 20
      az: 267
    - alt: 28
      az: 330
    - alt: 31
      az: 343
    - alt: 20
      az: 360

features:
  # Enable or disable festures
  horizon: true
  objects: true
  bodies: false
  comets: false
